#!/bin/bash

# Directory to store images
DIR=/var/lib/libvirt/images/

case $1 in
  jenkins)
    IP=192.168.122.11
    if [[ $2 == "server" ]]; then
    virsh destroy gitlab --no-autostart 2> /dev/null
    virt-install --name $1 --import --memory 2048 --vcpus 2 --disk $DIR/jenkins.qcow2 --os-variant ubuntu18.04 --network bridge=virbr0,model=virtio --noautoconsol e --autostart
    elif [[ $2 == "node" ]]; then
      virt-install --name ${1}-${2} --import --memory 2048 --vcpus 1 --disk $DIR/jenkins-node.qcow2 --os-variant ubuntu18.04 --network bridge=virbr0,model=virtio --noautoconsole --autostart
    else
	echo "Please, select jenkins server or node."
	exit 1
    fi
    ;;
  gitlab)
    IP=192.168.122.11
    virsh destroy jenkins --no-autostart 2> /dev/null
    virt-install --name $1 --import --memory 2048 --vcpus 2 --disk gitlab.qcow2 --os-variant ubuntu18.04 --network bridge=virbr0,model=virtio --noautoconsole --autostart
    ;;
  workstation)
    IP=192.168.122.10
    virt-install --name $1 --import --memory 4096 --vcpus 2 --disk ubuntu-workstation.qcow2 --os-variant ubuntu18.04 --network bridge=virbr0,model=virtio --noautoconsole --autostart
    ;;
  registry)
    IP=192.168.122.14
    ;;
  list)
    virsh list --all
    exit 1
    ;;
  *)
    echo "Invalid option, the options are: jenkins|gitlab workstation registry list"
    exit 1;;
esac

# Check if domain already exists
virsh dominfo $1 > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    echo -n "[WARNING] $1 already exists.  "
    read -p "Do you want to overwrite $1 [y/N]? " -r
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo ""
    else
        echo -e "\nNot overwriting $1. Exiting..."
        exit 1
    fi
fi
